use std::collections::HashMap;
use std::fs;

use chrono::{DateTime, Duration, Utc};

use crate::config::Config;
use crate::db::Database;
use crate::db::commit_store;
use crate::db::repo_store;
use crate::health::compute_health;

pub fn run(config: &Config) -> anyhow::Result<()> {
    let db = Database::open(&config.db_path())?;
    let index_path = config.index_path()?;

    let repos = db.tx(|conn| repo_store::get_all_repos(conn))?;
    if repos.is_empty() {
        anyhow::bail!("No repos synced. Run `pidx sync` first.");
    }

    let thirty_days_ago = (Utc::now() - Duration::days(30))
        .format("%Y-%m-%dT%H:%M:%SZ")
        .to_string();

    // Build category display name mapping from config
    let category_titles: HashMap<&str, &str> = config
        .categories
        .iter()
        .map(|c| (c.key.as_str(), c.title.as_str()))
        .collect();

    // Group repos by category, preserving config order
    let mut category_order: Vec<String> = Vec::new();
    let mut by_category: HashMap<String, Vec<RepoIndexEntry>> = HashMap::new();

    // Build config description overrides
    let config_descriptions: HashMap<&str, &str> = config
        .repos
        .iter()
        .filter_map(|r| r.description.as_deref().map(|d| (r.name.as_str(), d)))
        .collect();

    // Use config order for repos (which determines category encounter order)
    let config_repo_order: HashMap<&str, usize> = config
        .repos
        .iter()
        .enumerate()
        .map(|(i, r)| (r.name.as_str(), i))
        .collect();

    let mut sorted_repos = repos.clone();
    sorted_repos.sort_by_key(|r| config_repo_order.get(r.name.as_str()).copied().unwrap_or(999));

    for repo in &sorted_repos {
        let cat = repo.category.clone().unwrap_or_else(|| "other".to_string());

        if !by_category.contains_key(&cat) {
            category_order.push(cat.clone());
        }

        let commits_30d = db.tx(|conn| {
            commit_store::count_commits_since(conn, repo.id, &thirty_days_ago)
        })?;

        let last_pushed: Option<DateTime<Utc>> = repo
            .pushed_at
            .as_deref()
            .and_then(|s| s.parse().ok());

        let health = compute_health(last_pushed, commits_30d, repo.open_issues as u32);

        by_category.entry(cat).or_default().push(RepoIndexEntry {
            name: repo.name.clone(),
            owner: repo.owner.clone(),
            language: repo.language.clone().unwrap_or_else(|| "-".to_string()),
            description: config_descriptions
                .get(repo.name.as_str())
                .map(|s| s.to_string())
                .or_else(|| repo.description.clone())
                .unwrap_or_default(),
            health_label: health.label.as_str().to_string(),
            health_color: health.label.shield_color().to_string(),
            health_score: health.total,
        });
    }

    // Generate README
    let mut out = String::new();
    out.push_str("# Project Index\n\n");
    out.push_str("A catalog of my open-source projects.\n\n");
    out.push_str(&format!(
        "<!-- Generated by pidx on {} -->\n\n",
        Utc::now().format("%Y-%m-%d %H:%M UTC")
    ));
    out.push_str("## Active Projects (2026)\n\n");

    for cat in &category_order {
        let title = category_titles
            .get(cat.as_str())
            .copied()
            .unwrap_or(cat.as_str());

        out.push_str(&format!("### {title}\n\n"));
        out.push_str("| Project | Language | Description |\n");
        out.push_str("|---------|----------|-------------|\n");

        if let Some(entries) = by_category.get(cat) {
            for entry in entries {
                out.push_str(&format!(
                    "| [{}](https://github.com/{}/{}) | {} | {} |\n",
                    entry.name, entry.owner, entry.name, entry.language, entry.description,
                ));
            }
        }

        out.push('\n');
    }

    // Status dashboard — one row per repo, one column per signal.
    // Kept separate from the project list so the descriptions stay
    // readable and the at-a-glance health view is in one scannable
    // table. Repos appear in the same order as the project list (config
    // order grouped by category) so the two sections read as parallel.
    out.push_str("## Status Dashboard\n\n");
    out.push_str("| Project | CI | Last commit | Issues | PRs | License | Health |\n");
    out.push_str("|---------|----|-------------|--------|-----|---------|--------|\n");
    for cat in &category_order {
        if let Some(entries) = by_category.get(cat) {
            for entry in entries {
                out.push_str(&render_dashboard_row(entry));
            }
        }
    }
    out.push('\n');

    fs::write(&index_path, &out)?;
    println!("Updated index at {}", index_path.display());

    Ok(())
}

struct RepoIndexEntry {
    name: String,
    owner: String,
    language: String,
    description: String,
    health_label: String,
    health_color: String,
    #[allow(dead_code)]
    health_score: f64,
}

/// Render one row of the Status Dashboard table.
///
/// Seven columns: the project link, then six shields.io badges (all
/// flat-square, no inline `label=` text — the column header carries
/// the name so the badge can show only its value). Order matches the
/// table header in `run`:
///   1. Project (linked)
///   2. CI workflow status (always points at `ci.yml`)
///   3. Last commit (activity recency — surfaces stale repos)
///   4. Open issue count
///   5. Open PR count
///   6. License (quick legal scan)
///   7. Health label, colored by `HealthLabel::shield_color()`
fn render_dashboard_row(e: &RepoIndexEntry) -> String {
    let project = format!("[{}](https://github.com/{}/{})", e.name, e.owner, e.name);
    let ci = format!(
        "![CI](https://img.shields.io/github/actions/workflow/status/{}/{}/ci.yml?branch=main&style=flat-square&label=)",
        e.owner, e.name,
    );
    let last_commit = format!(
        "![Last commit](https://img.shields.io/github/last-commit/{}/{}?style=flat-square&label=)",
        e.owner, e.name,
    );
    let issues = format!(
        "![Issues](https://img.shields.io/github/issues/{}/{}?style=flat-square&label=)",
        e.owner, e.name,
    );
    let prs = format!(
        "![PRs](https://img.shields.io/github/issues-pr/{}/{}?style=flat-square&label=)",
        e.owner, e.name,
    );
    let license = format!(
        "![License](https://img.shields.io/github/license/{}/{}?style=flat-square&label=)",
        e.owner, e.name,
    );
    let health = format!(
        "![Health](https://img.shields.io/badge/{}-{}?style=flat-square)",
        e.health_label, e.health_color,
    );
    format!("| {project} | {ci} | {last_commit} | {issues} | {prs} | {license} | {health} |\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(owner: &str, name: &str, label: &str, color: &str) -> RepoIndexEntry {
        RepoIndexEntry {
            name: name.into(),
            owner: owner.into(),
            language: "Rust".into(),
            description: "x".into(),
            health_label: label.into(),
            health_color: color.into(),
            health_score: 80.0,
        }
    }

    #[test]
    fn dashboard_row_emits_seven_pipe_separated_cells() {
        // Arrange / Act
        let row = render_dashboard_row(&entry("Shuozeli", "protobuf-rs", "Active", "brightgreen"));

        // Assert: 7 cells (project + 6 badges) means 8 pipes plus the
        // trailing newline. Locking the cell count keeps a future
        // contributor from silently widening the dashboard table
        // without updating the header.
        let cell_count = row.matches('|').count();
        assert_eq!(cell_count, 8, "expected 7 cells (8 pipes), got row: {row}");
        assert!(row.ends_with('\n'));
    }

    #[test]
    fn dashboard_row_includes_all_six_badge_kinds() {
        // Arrange / Act
        let row = render_dashboard_row(&entry("Shuozeli", "protobuf-rs", "Active", "brightgreen"));

        // Assert: every badge URL fragment is present.
        assert!(row.contains("/github/actions/workflow/status/Shuozeli/protobuf-rs/ci.yml"));
        assert!(row.contains("/github/last-commit/Shuozeli/protobuf-rs"));
        assert!(row.contains("/github/issues/Shuozeli/protobuf-rs"));
        assert!(row.contains("/github/issues-pr/Shuozeli/protobuf-rs"));
        assert!(row.contains("/github/license/Shuozeli/protobuf-rs"));
        assert!(row.contains("/badge/Active-brightgreen"));
    }

    #[test]
    fn dashboard_row_uses_owner_per_entry() {
        // stonedb lives under github.com/stonedb/stonedb, not Shuozeli — verify
        // we don't hardcode the owner across any of the six badge kinds
        // OR the project link.
        let row = render_dashboard_row(&entry("stonedb", "stonedb", "Healthy", "green"));
        assert!(row.contains("[stonedb](https://github.com/stonedb/stonedb)"));
        assert!(row.contains("/github/actions/workflow/status/stonedb/stonedb/ci.yml"));
        assert!(row.contains("/github/last-commit/stonedb/stonedb"));
        assert!(row.contains("/github/issues/stonedb/stonedb"));
        assert!(row.contains("/github/issues-pr/stonedb/stonedb"));
        assert!(row.contains("/github/license/stonedb/stonedb"));
    }

    #[test]
    fn dashboard_row_propagates_color_from_label() {
        let dormant = render_dashboard_row(&entry("Shuozeli", "x", "Dormant", "lightgrey"));
        assert!(dormant.contains("/badge/Dormant-lightgrey"));
    }

    #[test]
    fn dashboard_row_orders_columns_left_to_right_for_visual_scanning() {
        // Order: project | CI | last commit | issues | PRs | license | health.
        // Pin so a future drive-by reorder is a deliberate choice.
        let row = render_dashboard_row(&entry("Shuozeli", "x", "Active", "brightgreen"));
        let project_idx = row.find("[x](https://github.com/Shuozeli/x)").unwrap();
        let ci_idx = row.find("/actions/workflow/status/").unwrap();
        let last_idx = row.find("/last-commit/").unwrap();
        let issues_idx = row.find("/issues/Shuozeli/x").unwrap();
        let prs_idx = row.find("/issues-pr/").unwrap();
        let license_idx = row.find("/license/").unwrap();
        let health_idx = row.find("/badge/Active-").unwrap();
        assert!(project_idx < ci_idx);
        assert!(ci_idx < last_idx);
        assert!(last_idx < issues_idx);
        assert!(issues_idx < prs_idx);
        assert!(prs_idx < license_idx);
        assert!(license_idx < health_idx);
    }
}
