use std::collections::HashMap;
use std::fs;

use chrono::{DateTime, Duration, Utc};

use crate::config::Config;
use crate::db::Database;
use crate::db::commit_store;
use crate::db::repo_store;
use crate::health::compute_health;

pub fn run(config: &Config) -> anyhow::Result<()> {
    let db = Database::open(&config.db_path())?;
    let index_path = config.index_path()?;

    let repos = db.tx(|conn| repo_store::get_all_repos(conn))?;
    if repos.is_empty() {
        anyhow::bail!("No repos synced. Run `pidx sync` first.");
    }

    let thirty_days_ago = (Utc::now() - Duration::days(30))
        .format("%Y-%m-%dT%H:%M:%SZ")
        .to_string();

    // Build category display name mapping from config
    let category_titles: HashMap<&str, &str> = config
        .categories
        .iter()
        .map(|c| (c.key.as_str(), c.title.as_str()))
        .collect();

    // Group repos by category, preserving config order
    let mut category_order: Vec<String> = Vec::new();
    let mut by_category: HashMap<String, Vec<RepoIndexEntry>> = HashMap::new();

    // Build config description overrides
    let config_descriptions: HashMap<&str, &str> = config
        .repos
        .iter()
        .filter_map(|r| r.description.as_deref().map(|d| (r.name.as_str(), d)))
        .collect();

    // Use config order for repos (which determines category encounter order)
    let config_repo_order: HashMap<&str, usize> = config
        .repos
        .iter()
        .enumerate()
        .map(|(i, r)| (r.name.as_str(), i))
        .collect();

    let mut sorted_repos = repos.clone();
    sorted_repos.sort_by_key(|r| config_repo_order.get(r.name.as_str()).copied().unwrap_or(999));

    for repo in &sorted_repos {
        let cat = repo.category.clone().unwrap_or_else(|| "other".to_string());

        if !by_category.contains_key(&cat) {
            category_order.push(cat.clone());
        }

        let commits_30d = db.tx(|conn| {
            commit_store::count_commits_since(conn, repo.id, &thirty_days_ago)
        })?;

        let last_pushed: Option<DateTime<Utc>> = repo
            .pushed_at
            .as_deref()
            .and_then(|s| s.parse().ok());

        let health = compute_health(last_pushed, commits_30d, repo.open_issues as u32);

        by_category.entry(cat).or_default().push(RepoIndexEntry {
            name: repo.name.clone(),
            owner: repo.owner.clone(),
            language: repo.language.clone().unwrap_or_else(|| "-".to_string()),
            description: config_descriptions
                .get(repo.name.as_str())
                .map(|s| s.to_string())
                .or_else(|| repo.description.clone())
                .unwrap_or_default(),
            health_label: health.label.as_str().to_string(),
            health_color: health.label.shield_color().to_string(),
            health_score: health.total,
        });
    }

    // Generate README
    let mut out = String::new();
    out.push_str("# Project Index\n\n");
    out.push_str("A catalog of my open-source projects.\n\n");
    out.push_str(&format!(
        "<!-- Generated by pidx on {} -->\n\n",
        Utc::now().format("%Y-%m-%d %H:%M UTC")
    ));
    out.push_str("## Active Projects (2026)\n\n");

    for cat in &category_order {
        let title = category_titles
            .get(cat.as_str())
            .copied()
            .unwrap_or(cat.as_str());

        out.push_str(&format!("### {title}\n\n"));
        out.push_str("| Project | Language | Description | Status |\n");
        out.push_str("|---------|----------|-------------|--------|\n");

        if let Some(entries) = by_category.get(cat) {
            for entry in entries {
                out.push_str(&format!(
                    "| [{}](https://github.com/{}/{}) | {} | {} | {} |\n",
                    entry.name,
                    entry.owner,
                    entry.name,
                    entry.language,
                    entry.description,
                    render_status_badges(entry),
                ));
            }
        }

        out.push('\n');
    }

    fs::write(&index_path, &out)?;
    println!("Updated index at {}", index_path.display());

    Ok(())
}

struct RepoIndexEntry {
    name: String,
    owner: String,
    language: String,
    description: String,
    health_label: String,
    health_color: String,
    #[allow(dead_code)]
    health_score: f64,
}

/// Render the inline shields.io badges for a repo's Status cell.
///
/// Six badges, all flat-square, ordered for left-to-right scanning
/// (health-first, then activity, then backlog, then metadata):
///   1. CI workflow status (always points at `ci.yml`)
///   2. Last commit (activity recency — surfaces stale repos)
///   3. Open issue count
///   4. Open PR count
///   5. License (quick legal scan)
///   6. Health label, colored by `HealthLabel::shield_color()`
fn render_status_badges(e: &RepoIndexEntry) -> String {
    let ci = format!(
        "![CI](https://img.shields.io/github/actions/workflow/status/{}/{}/ci.yml?branch=main&style=flat-square&label=CI)",
        e.owner, e.name,
    );
    let last_commit = format!(
        "![Last commit](https://img.shields.io/github/last-commit/{}/{}?style=flat-square&label=last)",
        e.owner, e.name,
    );
    let issues = format!(
        "![Issues](https://img.shields.io/github/issues/{}/{}?style=flat-square&label=issues)",
        e.owner, e.name,
    );
    let prs = format!(
        "![PRs](https://img.shields.io/github/issues-pr/{}/{}?style=flat-square&label=PRs)",
        e.owner, e.name,
    );
    let license = format!(
        "![License](https://img.shields.io/github/license/{}/{}?style=flat-square)",
        e.owner, e.name,
    );
    let health = format!(
        "![Health](https://img.shields.io/badge/health-{}-{}?style=flat-square)",
        e.health_label, e.health_color,
    );
    format!("{ci} {last_commit} {issues} {prs} {license} {health}")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(owner: &str, name: &str, label: &str, color: &str) -> RepoIndexEntry {
        RepoIndexEntry {
            name: name.into(),
            owner: owner.into(),
            language: "Rust".into(),
            description: "x".into(),
            health_label: label.into(),
            health_color: color.into(),
            health_score: 80.0,
        }
    }

    #[test]
    fn status_badges_emits_all_six_badge_kinds() {
        // Arrange / Act
        let s = render_status_badges(&entry("Shuozeli", "protobuf-rs", "Active", "brightgreen"));

        // Assert: every badge URL we promised is present, in any order
        // the formatter produces.
        assert!(s.contains("/github/actions/workflow/status/Shuozeli/protobuf-rs/ci.yml"));
        assert!(s.contains("/github/last-commit/Shuozeli/protobuf-rs"));
        assert!(s.contains("/github/issues/Shuozeli/protobuf-rs"));
        assert!(s.contains("/github/issues-pr/Shuozeli/protobuf-rs"));
        assert!(s.contains("/github/license/Shuozeli/protobuf-rs"));
        assert!(s.contains("badge/health-Active-brightgreen"));
    }

    #[test]
    fn status_badges_use_owner_per_entry() {
        // stonedb lives under github.com/stonedb/stonedb, not Shuozeli — verify
        // we don't hardcode the owner across any of the six badge kinds.
        let s = render_status_badges(&entry("stonedb", "stonedb", "Healthy", "green"));
        assert!(s.contains("/github/actions/workflow/status/stonedb/stonedb/ci.yml"));
        assert!(s.contains("/github/last-commit/stonedb/stonedb"));
        assert!(s.contains("/github/issues/stonedb/stonedb"));
        assert!(s.contains("/github/issues-pr/stonedb/stonedb"));
        assert!(s.contains("/github/license/stonedb/stonedb"));
    }

    #[test]
    fn status_badges_propagate_color_from_label() {
        let dormant = render_status_badges(&entry("Shuozeli", "x", "Dormant", "lightgrey"));
        assert!(dormant.contains("badge/health-Dormant-lightgrey"));
    }

    #[test]
    fn status_badges_render_left_to_right_health_first() {
        // The order is load-bearing for visual scanning: CI is the
        // most important at-a-glance signal, then activity recency,
        // then backlog (issues then PRs), then license, then the
        // pidx-derived health roll-up. This test pins that order so
        // a reorder is a deliberate choice rather than a drive-by.
        let s = render_status_badges(&entry("Shuozeli", "x", "Active", "brightgreen"));
        let ci_idx = s.find("/actions/workflow/status/").unwrap();
        let last_idx = s.find("/last-commit/").unwrap();
        let issues_idx = s.find("/issues/Shuozeli/x").unwrap();
        let prs_idx = s.find("/issues-pr/").unwrap();
        let license_idx = s.find("/license/").unwrap();
        let health_idx = s.find("badge/health-").unwrap();
        assert!(ci_idx < last_idx);
        assert!(last_idx < issues_idx);
        assert!(issues_idx < prs_idx);
        assert!(prs_idx < license_idx);
        assert!(license_idx < health_idx);
    }
}
